### ISSUE TITLE
Changing the array of options not refresh de view until click in another element

### ISSUE THREAD

**Issue by ffradegrada** [adityasharat/angular-chosen#33]
Because of my business, I am changing (removing one option) the array of options when the select it's already initialized. This does not refresh the view, until I click in another option.

Do you know what may be going on? Here's my code:

Controller:

```
$scope.users = [];
$scope.myOptions= [ { "id":"1", "name":"Fernando" } , { "id":"2", "name":"Gerardo" } ];

$scope.onClick = function() {
    $scope.myOptions.splice(1,1); //I am harcoding the code, so it's easier to read.
};
```

HTML:

```
<select multiple chosen
      class="chosen-select"
      ng-model="users"
      ng-options="{ id: opt.id } as opt.name for opt in myOptions track by opt.id">
      <option value=""></option>
</select>
```

**Comment by adityasharat** [comment]
since you are modifying `$scope.myOptions` by doing the following `$scope.myOptions.splice(1,1)` it triggers the change event in the chosen directive. That is because inside the directive it is `watching` the array for changes, to maintain consistency.
Ideally, if you want to do that on your own, it is better to have 2 copies of the array. One assigned to the `options` and the other one which you modify as you please. One done, assign the modified on to the `chosen`.
I hope I understood the problem correctly.

**Comment by adityasharat** [comment]
``` html
<select multiple chosen
      options="myOptions" // missing attribute
      class="chosen-select"
      ng-model="users"
      ng-options="{ id: opt.id } as opt.name for opt in myOptions track by opt.id">
      <option value=""></option>
</select>
```

**Comment by adityasharat** [comment]
@ffradegrada did it work? If so please close the issue.
