### ISSUE TITLE
Loading angular before jquery and chosen

### ISSUE THREAD

**Issue by Dervisevic** [adityasharat/angular-chosen#4]
Hi, so I've noticed the same issue with both here and  over at wangshijun/angular-bootstrap-chosen#1. If you load angular before jquery and chosen you will get that chosen isn't a function on the element. The github page doesn't reflect on when angular should be loaded. I might make a PR to address it so it becomes more clear, and the only way i found it out was copying your script tags on the gh-page.

**Comment by adityasharat** [comment]
If you load angular before jquery, the element you get in the linker of the directive is a [jqLite](https://docs.angularjs.org/api/ng/function/angular.element) element and not a jQuery element.
So it won't have the `chosen` function on it.

If you load jQuery before angular, angular will use jQuery instead of jqLite.
Pease raise a PR :) if you can make it point clear.

**Comment by Dervisevic** [comment]
Yeah, i figured that point out later, stupid me :( You have a really nice guide on the gh page, it has everything except angular, so yeah I'll take a whack at that later, just to make it super clear. Great addon btw!

**Comment by adityasharat** [comment]
Issue fixed
